// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCB4fXbg8UFnJtEYsMy3Mn_kNfKsrj3zy0',
    appId: '1:458935581305:web:1bb9e087aeb4ed937572a8',
    messagingSenderId: '458935581305',
    projectId: 'zapatito-26b68',
    authDomain: 'zapatito-26b68.firebaseapp.com',
    storageBucket: 'zapatito-26b68.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLPBEocUGsqnt6DTFpJKsMUmjBCP1QgTE',
    appId: '1:458935581305:android:037b36def093e0117572a8',
    messagingSenderId: '458935581305',
    projectId: 'zapatito-26b68',
    storageBucket: 'zapatito-26b68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFBTQ-uR0dyWjO0QfO4Ge623HNePBlH9k',
    appId: '1:458935581305:ios:969567078bb76da07572a8',
    messagingSenderId: '458935581305',
    projectId: 'zapatito-26b68',
    storageBucket: 'zapatito-26b68.firebasestorage.app',
    iosBundleId: 'com.example.zapatito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFBTQ-uR0dyWjO0QfO4Ge623HNePBlH9k',
    appId: '1:458935581305:ios:969567078bb76da07572a8',
    messagingSenderId: '458935581305',
    projectId: 'zapatito-26b68',
    storageBucket: 'zapatito-26b68.firebasestorage.app',
    iosBundleId: 'com.example.zapatito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCB4fXbg8UFnJtEYsMy3Mn_kNfKsrj3zy0',
    appId: '1:458935581305:web:0aeca95030602f9e7572a8',
    messagingSenderId: '458935581305',
    projectId: 'zapatito-26b68',
    authDomain: 'zapatito-26b68.firebaseapp.com',
    storageBucket: 'zapatito-26b68.firebasestorage.app',
  );

}